### ISSUE TITLE
ChrAccR vs ArchR?

### ISSUE THREAD

**Issue by mfisher1995** [GreenleafLab/ChrAccR#1]
Hello, I am a user of ArchR for about a year now and have come across ChrAccR just by browsing the GreenleafLab GitHub page. I'm curious how ChrAccR plans to be advantageous in comparison to ArchR, would love to know more about the motivations for this tool. Thanks.

**Comment by demuellae** [comment]
Dear Maggie,
ArchR provides a great toolset for single-cell analysis. ChrAccR was first designed to provide a comprehensive pipeline and utilities for the analysis of bulk data. Then, we started to implement selected single-cell functionality in order to be able to quickly try out and prototype new methods in the rapidly changing field single-cell. In the meantime, ArchR  set out to really make an effort on efficicient and robust implementation of a comprehensive set of single-cell methods.  So, in brief, here's how I use the tools: ChrAccR for bulk analysis and playing around with single-cell data, ArchR for robust and efficient analysis of single-cell data using established methods. I am happy to chat more about the functionality of the tools and discuss what the right tool would be for your project. Hope that helps!
